# Generated by Django 3.2.7 on 2021-10-17 09:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='favourites',
            field=models.ManyToManyField(blank=True, default=None, related_name='favourite_project', to=settings.AUTH_USER_MODEL),
        ),
    ]
